name: Tests

on:
  - push
  - pull_request

jobs:

  test_all_coverage:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
          pip install -e .
      - name: Test with pytest
        run: pytest --cov=./ --cov-report=xml
      